### PR TITLE
Bump React Native client version to v1.0.7

### PR DESCRIPTION
**Pull request by vishnumad**
### _Summary_
* Update code owners
* Revert previous version bump PR
* Manually bump RN client to 1.0.7

### _How did you test your changes?_
n/a

### CODE REVIEW

**Review by bangtoven — APPROVED** [review]

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 03:48:20 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 03:48:31 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 03:54:05 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 04:57:12 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 05:41:48 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 05:49:12 UTC
User must have write permissions to review

**Review by Brandylee24 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Brandylee24 @ 2023-08-06 13:33:43 UTC
User must have write permissions to review

**Review by Brandylee24 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Brandylee24 @ 2023-08-06 13:35:29 UTC
User must have write permissions to review

**Pull request merged**
