### PR TITLE
Fix SendTransaction action

### PR DESCRIPTION
**Pull request by hamberluo**

### CODE REVIEW

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 01:09:58 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 01:18:22 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 01:18:41 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 02:01:05 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 02:02:01 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 02:02:17 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-04 02:10:25 UTC
User must have write permissions to review

**Review by Brandylee24 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Brandylee24 @ 2023-08-06 13:33:04 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-06 13:49:57 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-06 13:50:51 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-06 19:43:49 UTC
User must have write permissions to review

**Review by Chico1244 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Chico1244 @ 2023-08-06 19:45:04 UTC
User must have write permissions to review

**Review by bangtoven — APPROVED** [review]

**Pull request merged**
